import type { Edge, Enrichment, Group, MatterRole, Person, Workplace } from "./types";

const YOU: Person = {
  id: "you",
  name: "Alex Rowan",
  role: "Senior Product Manager",
  team: "Platform",
  department: "Product",
  location: "London",
  you: true,
  tags: ["weak-tie"],
  bio: "Three years at Harbourline. Owns the platform usage surface — APIs, entitlements, and the bits Sales promises before Engineering has agreed.",
  groups: ["product-platform", "shipping-guild"],
};

const PEOPLE: Person[] = [
  YOU,
  {
    id: "louise",
    name: "Louise Wright",
    role: "Principal Product Manager",
    team: "Platform",
    department: "Product",
    location: "London",
    tags: ["manager"],
    bio: "Your manager. Will write a strong packet. Not in the pay-review room.",
    groups: ["product-platform", "shipping-guild"],
  },
  {
    id: "nadia",
    name: "Nadia Okonkwo",
    role: "VP Product",
    team: "Product",
    department: "Leadership",
    location: "London",
    tags: ["sponsor"],
    bio: "Decides product promotions with Callum and Sian. Hears craft more than theatre. Needs engineers to say your name when you are not in the room.",
    groups: ["elt", "product-platform"],
  },
  {
    id: "mei",
    name: "Mei Lin",
    role: "Product Manager",
    team: "Growth",
    department: "Product",
    location: "Manchester",
    bio: "Owns activation. Useful when a platform change lands in the first-run flow.",
    groups: ["product-growth"],
  },
  {
    id: "harun",
    name: "Harun Çelik",
    role: "Product Manager",
    team: "Billing",
    department: "Product",
    location: "London",
    bio: "Sits on every pricing thread whether invited or not. Knows Finance's real objections.",
    groups: ["product-platform"],
  },
  {
    id: "benito",
    name: "Benito Cruz",
    role: "Product Operations",
    team: "Product Ops",
    department: "Product",
    location: "London",
    bio: "Runs the roadmap ritual. Quietly knows which initiatives are already dead.",
    groups: ["product-platform"],
  },
  {
    id: "anika",
    name: "Anika Rao",
    role: "Product Designer",
    team: "Platform",
    department: "Product",
    location: "London",
    bio: "Design partner on entitlements. Trusted by Engineering because she ships with them.",
    groups: ["product-platform", "shipping-guild"],
  },
  {
    id: "chris",
    name: "Chris Phelan",
    role: "Product Designer",
    team: "Growth",
    department: "Product",
    location: "Bristol",
    bio: "Growth design. Occasional pairing on empty states.",
    groups: ["product-growth"],
  },
  {
    id: "priya",
    name: "Priya Shah",
    role: "Staff Engineer",
    team: "Platform",
    department: "Engineering",
    location: "London",
    tags: ["broker"],
    bio: "The person both Product and Engineering will take a meeting from. Carries architecture reviews and, unofficially, the translation layer.",
    groups: ["eng-platform", "shipping-guild"],
  },
  {
    id: "maya",
    name: "Maya Chen",
    role: "Engineering Manager",
    team: "Platform",
    department: "Engineering",
    location: "London",
    tags: ["fold", "manager"],
    bio: "Manages Platform engineering and sits in the shipping guild. Two dense rooms; she is in both. That overlap is a structural fold.",
    groups: ["eng-platform", "shipping-guild"],
  },
  {
    id: "dex",
    name: "Dex Williams",
    role: "Tech Lead",
    team: "Platform",
    department: "Engineering",
    location: "London",
    bio: "Day-to-day counterpart on the API surface. Will tell you the truth in a huddle and a softer version in Slack.",
    groups: ["eng-platform", "shipping-guild"],
  },
  {
    id: "owen",
    name: "Owen Griffiths",
    role: "Senior Engineer",
    team: "Platform",
    department: "Engineering",
    location: "Cardiff",
    bio: "Entitlements specialist. Respects people who read the code before the meeting.",
    groups: ["eng-platform"],
  },
  {
    id: "lila",
    name: "Lila Novak",
    role: "Engineer",
    team: "Platform",
    department: "Engineering",
    location: "London",
    bio: "New this year. Already the person who knows the on-call runbook.",
    groups: ["eng-platform"],
  },
  {
    id: "farhad",
    name: "Farhad Hussain",
    role: "Engineer",
    team: "Platform",
    department: "Engineering",
    location: "Birmingham",
    groups: ["eng-platform"],
  },
  {
    id: "niamh",
    name: "Niamh Byrne",
    role: "Staff Engineer, Data",
    team: "Data",
    department: "Engineering",
    location: "Dublin",
    tags: ["broker"],
    bio: "Connects Data, Product, and Finance whenever a metric is about to become a target.",
    groups: ["eng-data"],
  },
  {
    id: "jonas",
    name: "Jonas Berg",
    role: "Senior Engineer",
    team: "SRE",
    department: "Engineering",
    location: "London",
    bio: "Incident commander more often than he would like. You met during a nasty entitlements outage.",
    groups: ["eng-sre"],
  },
  {
    id: "aisha",
    name: "Aisha Rahman",
    role: "Engineer",
    team: "Growth",
    department: "Engineering",
    location: "Manchester",
    groups: ["eng-growth"],
  },
  {
    id: "rui",
    name: "Rui Santos",
    role: "Site Reliability Engineer",
    team: "SRE",
    department: "Engineering",
    location: "Lisbon / London",
    groups: ["eng-sre"],
  },
  {
    id: "paul",
    name: "Paul Okeke",
    role: "Engineering Manager",
    team: "Growth",
    department: "Engineering",
    location: "London",
    tags: ["manager"],
    groups: ["eng-growth"],
  },
  {
    id: "callum",
    name: "Callum Bright",
    role: "VP Engineering",
    team: "Engineering",
    department: "Leadership",
    location: "London",
    tags: ["sponsor"],
    bio: "In the room for product promotions that touch platform risk. You do not have a tie to him yet — that is the hole.",
    groups: ["elt", "eng-platform"],
  },
  {
    id: "samir",
    name: "Samir Patel",
    role: "Enterprise Account Executive",
    team: "Enterprise",
    department: "Sales",
    location: "London",
    tags: ["weak-tie"],
    bio: "You co-owned one awkward deal last autumn. A weak tie, still live. Knows which accounts would buy usage-based SKUs tomorrow.",
    groups: ["sales-ent"],
  },
  {
    id: "helen",
    name: "Helen Marsh",
    role: "Account Executive",
    team: "Mid-market",
    department: "Sales",
    location: "Leeds",
    groups: ["sales-mm"],
  },
  {
    id: "gareth",
    name: "Gareth Quinn",
    role: "Sales Engineer",
    team: "Enterprise",
    department: "Sales",
    location: "London",
    bio: "Translates platform constraints into something Sales can say out loud.",
    groups: ["sales-ent", "shipping-guild"],
  },
  {
    id: "imani",
    name: "Imani Boateng",
    role: "Regional Director",
    team: "Enterprise",
    department: "Sales",
    location: "London",
    tags: ["manager"],
    groups: ["sales-ent"],
  },
  {
    id: "nico",
    name: "Nico Alvarez",
    role: "SDR",
    team: "Outbound",
    department: "Sales",
    location: "Barcelona / London",
    groups: ["sales-mm"],
  },
  {
    id: "tom",
    name: "Tom Hale",
    role: "Principal Customer Success Manager",
    team: "Enterprise CS",
    department: "Customer Success",
    location: "London",
    tags: ["broker"],
    bio: "Broker between CS, Sales, and Product. If a customer will pay, Tom already has the quote in a doc.",
    groups: ["cs-ent", "shipping-guild"],
  },
  {
    id: "rebecca",
    name: "Rebecca Shaw",
    role: "Customer Success Manager",
    team: "Enterprise CS",
    department: "Customer Success",
    location: "Edinburgh",
    groups: ["cs-ent"],
  },
  {
    id: "daniel",
    name: "Daniel Cho",
    role: "Onboarding Lead",
    team: "Onboarding",
    department: "Customer Success",
    location: "London",
    groups: ["cs-onboarding"],
  },
  {
    id: "fatima",
    name: "Fatima Al-Sayed",
    role: "Support Lead",
    team: "Support",
    department: "Customer Success",
    location: "London",
    groups: ["cs-support"],
  },
  {
    id: "sian",
    name: "Sian Davies",
    role: "VP Customer",
    team: "Customer",
    department: "Leadership",
    location: "Cardiff / London",
    tags: ["sponsor"],
    bio: "Sits in calibration. Backs people who have made a customer's quarter easier.",
    groups: ["elt", "cs-ent"],
  },
  {
    id: "isla",
    name: "Isla McCabe",
    role: "Content Lead",
    team: "Brand",
    department: "Marketing",
    location: "Glasgow",
    tags: ["weak-tie"],
    bio: "Asked you for a platform blog last spring. The tie is thin; it still exists.",
    groups: ["mkt-brand"],
  },
  {
    id: "caitlin",
    name: "Caitlin Walsh",
    role: "Product Marketing Manager",
    team: "PMM",
    department: "Marketing",
    location: "London",
    bio: "Will need a narrative if the pricing experiment ships. Better as a co-author than a reviewer.",
    groups: ["mkt-pmm", "shipping-guild"],
  },
  {
    id: "theo",
    name: "Theo Nkrumah",
    role: "Demand Generation",
    team: "Growth Marketing",
    department: "Marketing",
    location: "London",
    groups: ["mkt-demand"],
  },
  {
    id: "fiona",
    name: "Fiona McLeod",
    role: "FP&A Partner",
    team: "Finance",
    department: "Finance",
    location: "Edinburgh",
    tags: ["weak-tie"],
    bio: "Met at the Brighton offsite. Not your stakeholder. The only warm path you have into Finance.",
    groups: ["fin-fpa"],
  },
  {
    id: "dominic",
    name: "Dominic Hargreaves",
    role: "Finance Director",
    team: "Finance",
    department: "Finance",
    location: "London",
    tags: ["manager"],
    bio: "Approves pricing experiments. Cold Slack from Product dies in his unread. He will read Fiona.",
    groups: ["fin-fpa"],
  },
  {
    id: "leila",
    name: "Leila Bouzid",
    role: "Billing Operations",
    team: "Finance Ops",
    department: "Finance",
    location: "London",
    bio: "Knows whether the billing system can actually do what the experiment requires.",
    groups: ["fin-ops"],
  },
  {
    id: "frances",
    name: "Frances Whitaker",
    role: "Counsel",
    team: "Legal",
    department: "Legal",
    location: "London",
    bio: "Will follow Finance on a pricing change. You have no direct tie. That is not a crisis if Finance is already with you.",
    groups: ["legal"],
  },
  {
    id: "bridget",
    name: "Bridget Okafor",
    role: "People Partner",
    team: "People",
    department: "People",
    location: "London",
    bio: "Runs the IC promotion process. Will not sponsor. Will tell you if the packet is thin.",
    groups: ["people"],
  },
  {
    id: "jordan",
    name: "Jordan Adeyemi",
    role: "Chief of Staff",
    team: "Office of the CEO",
    department: "Leadership",
    location: "London",
    tags: ["broker"],
    bio: "Broker between the ELT and ICs who still do the work. Knows how Eleanor hears 'scope' versus 'headcount'.",
    groups: ["elt"],
  },
  {
    id: "eleanor",
    name: "Eleanor Voss",
    role: "Chief Executive",
    team: "Leadership",
    department: "Leadership",
    location: "London",
    bio: "Does not need to know your name yet. Needs Nadia to be able to say it cleanly.",
    groups: ["elt"],
  },
];

function e(
  source: string,
  target: string,
  strength: 1 | 2 | 3 | 4 | 5,
  kind: Edge["kind"],
  label?: string,
): Edge {
  const [a, b] = source < target ? [source, target] : [target, source];
  return {
    id: `${a}__${b}__${kind}`,
    source,
    target,
    strength,
    kind,
    label,
  };
}

const EDGES: Edge[] = [
  e("you", "louise", 5, "reports", "manager"),
  e("louise", "nadia", 5, "reports"),
  e("nadia", "eleanor", 5, "reports"),
  e("callum", "eleanor", 5, "reports"),
  e("sian", "eleanor", 5, "reports"),
  e("jordan", "eleanor", 5, "reports"),
  e("dominic", "eleanor", 4, "reports"),
  e("priya", "maya", 4, "reports"),
  e("dex", "maya", 5, "reports"),
  e("owen", "maya", 5, "reports"),
  e("lila", "maya", 5, "reports"),
  e("farhad", "maya", 5, "reports"),
  e("maya", "callum", 5, "reports"),
  e("paul", "callum", 5, "reports"),
  e("aisha", "paul", 5, "reports"),
  e("jonas", "rui", 3, "collaborates"),
  e("rui", "callum", 4, "reports"),
  e("niamh", "callum", 4, "reports"),
  e("mei", "louise", 3, "reports"),
  e("harun", "louise", 4, "reports"),
  e("benito", "nadia", 4, "reports"),
  e("anika", "louise", 4, "collaborates"),
  e("chris", "mei", 4, "collaborates"),
  e("samir", "imani", 5, "reports"),
  e("helen", "imani", 4, "reports"),
  e("gareth", "imani", 4, "reports"),
  e("nico", "helen", 4, "reports"),
  e("imani", "sian", 3, "skip", "dotted into customer"),
  e("tom", "sian", 5, "reports"),
  e("rebecca", "tom", 5, "reports"),
  e("daniel", "sian", 4, "reports"),
  e("fatima", "sian", 4, "reports"),
  e("fiona", "dominic", 5, "reports"),
  e("leila", "dominic", 5, "reports"),
  e("frances", "eleanor", 3, "reports"),
  e("bridget", "eleanor", 4, "reports"),
  e("isla", "theo", 3, "collaborates"),
  e("caitlin", "nadia", 3, "skip"),

  e("you", "priya", 5, "collaborates", "daily platform pair"),
  e("you", "dex", 4, "collaborates"),
  e("you", "anika", 4, "collaborates"),
  e("you", "harun", 3, "collaborates", "pricing threads"),
  e("you", "benito", 3, "collaborates"),
  e("you", "caitlin", 3, "collaborates"),
  e("you", "tom", 3, "collaborates", "launch reviews"),
  e("you", "niamh", 3, "collaborates", "usage metrics"),
  e("you", "mei", 2, "collaborates"),
  e("louise", "maya", 4, "collaborates", "product/eng pair"),
  e("priya", "dex", 5, "collaborates"),
  e("priya", "owen", 4, "collaborates"),
  e("priya", "anika", 3, "collaborates"),
  e("priya", "gareth", 3, "collaborates"),
  e("dex", "owen", 4, "collaborates"),
  e("dex", "lila", 3, "collaborates"),
  e("tom", "samir", 4, "collaborates"),
  e("tom", "rebecca", 4, "collaborates"),
  e("tom", "gareth", 3, "collaborates"),
  e("tom", "caitlin", 3, "collaborates"),
  e("samir", "gareth", 4, "collaborates"),
  e("fiona", "leila", 3, "collaborates"),
  e("fiona", "niamh", 3, "collaborates", "forecast vs actuals"),
  e("frances", "dominic", 3, "collaborates"),
  e("jordan", "bridget", 4, "collaborates"),
  e("jordan", "nadia", 4, "collaborates"),
  e("jordan", "callum", 3, "collaborates"),
  e("caitlin", "isla", 3, "collaborates"),
  e("fatima", "daniel", 3, "collaborates"),
  e("paul", "mei", 4, "collaborates"),
  e("aisha", "chris", 3, "collaborates"),
  e("maya", "tom", 3, "collaborates", "shipping guild"),
  e("maya", "caitlin", 2, "collaborates"),
  e("louise", "tom", 3, "collaborates"),

  e("you", "fiona", 2, "weak", "Brighton offsite"),
  e("you", "samir", 2, "weak", "one enterprise deal"),
  e("you", "isla", 1, "weak", "asked for a blog"),
  e("you", "jonas", 2, "weak", "entitlements incident"),
  e("you", "nadia", 2, "skip", "rare skip-level"),
  e("you", "jordan", 1, "weak", "not yet a coffee"),
  e("priya", "niamh", 2, "weak"),
  e("priya", "callum", 3, "skip"),
  e("tom", "dominic", 2, "weak", "renewal forecast"),
  e("gareth", "owen", 2, "weak"),
  e("bridget", "louise", 3, "collaborates", "people partner"),
];

const GROUPS: Group[] = [
  {
    id: "elt",
    name: "Executive group",
    blurb: "The room that actually decides promotions and pricing exceptions.",
    memberIds: ["eleanor", "nadia", "callum", "sian", "jordan"],
  },
  {
    id: "product-platform",
    name: "Platform product",
    blurb: "The product cluster around entitlements and APIs.",
    memberIds: ["you", "louise", "harun", "benito", "anika", "nadia"],
  },
  {
    id: "eng-platform",
    name: "Platform engineering",
    blurb: "A dense engineering clique. Maya manages it; Priya sets the technical weather.",
    memberIds: ["maya", "priya", "dex", "owen", "lila", "farhad", "callum"],
  },
  {
    id: "shipping-guild",
    name: "Shipping guild",
    blurb: "Cross-department launch circle — Product, Engineering, CS, PMM. Maya and Priya sit in both this and Platform engineering.",
    memberIds: ["you", "louise", "anika", "priya", "maya", "dex", "tom", "gareth", "caitlin"],
  },
  {
    id: "cs-ent",
    name: "Enterprise CS",
    blurb: "Customer cluster that knows who will pay.",
    memberIds: ["tom", "rebecca", "sian"],
  },
  {
    id: "fin-fpa",
    name: "Finance control",
    blurb: "The path a pricing experiment must walk.",
    memberIds: ["fiona", "dominic"],
  },
];

export function buildHarbourlineWorkplace(profile?: {
  name: string;
  role: string;
  team: string;
  company?: string;
  intent: Workplace["profile"]["intent"];
}): Workplace {
  const people = PEOPLE.map((person) => {
    const base = person.you
      ? {
          ...person,
          name: profile?.name ?? person.name,
          role: profile?.role ?? person.role,
          team: profile?.team ?? person.team,
        }
      : { ...person };
    if (base.you) {
      return { ...base, company: profile?.company ?? "Harbourline", layer: "workplace" as const };
    }
    let matter: MatterRole = "peer";
    if (base.tags?.includes("sponsor")) matter = "sponsor";
    else if (base.tags?.includes("broker")) matter = "broker";
    else if (base.tags?.includes("manager")) matter = "decision_maker";
    else if (base.tags?.includes("fold")) matter = "broker";
    const tie = base.tags?.includes("weak-tie") ? "weak" : "working";
    const enrichment: Enrichment = {
      team: base.department,
      matter,
      tie,
    };
    return {
      ...base,
      company: "Harbourline",
      layer: "workplace" as const,
      enrichment,
    };
  });

  return {
    version: 1,
    onboarded: true,
    source: "demo",
    workplaceName: "Harbourline",
    workplaceBlurb:
      "UK B2B SaaS. Operations OS for mid-market logistics. London HQ, about ninety people. This map is the slice an IC can actually see — not the official chart.",
    profile: {
      name: profile?.name ?? YOU.name,
      role: profile?.role ?? YOU.role,
      team: profile?.team ?? YOU.team,
      company: profile?.company ?? "Harbourline",
      intent: profile?.intent ?? "see-the-room",
    },
    people,
    edges: EDGES.map((edge) => ({ ...edge })),
    groups: GROUPS.map((group) => ({ ...group, memberIds: [...group.memberIds] })),
    company: profile?.company ?? "Harbourline",
    includeWorkplace: true,
    includePersonal: false,
    enrichmentSkipped: false,
  };
}
